sequenceDiagram
    client->>pc: request_shutdown
    activate pc
    pc-->>client: {challenge}

    Note right of client: command = shutdown|admin_shutdown
    client-->>pc: (command).{challenge}.{hmac}

    Note right of client: hmac = HMAC_SHA256(secret, "(command).{challenge}")
    alt success
        rect rgb(200, 255, 200)
            pc-->>client: "1"
        end
    else error
        rect rgb(255, 200, 200)
            pc-->>client: "error description"
        end
    end
    deactivate pc
